[package]
name = "inline"
version = "0.20220713.0"
edition = "2021"
authors = ["Jeremy Banks"]
license = "MIT OR Apache-2.0"
description = "Self-modifying values that update their source code at runtime"
repository = "https://github.com/jeremyBanks/inline"
homepage = "https://github.com/jeremyBanks/inline"
documentation = "https://docs.rs/inline"
readme = "README.md"
keywords = ["snapshot", "testing", "self-modifying", "codegen"]
categories = ["development-tools::testing", "development-tools"]

[dependencies]
once_cell = "1.13.0"
databake = "0.1"
syn = { version = "2", features = ["full", "visit-mut", "visit", "extra-traits"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
prettyplease = "0.2"
parking_lot = "0.12"

[dev-dependencies]
tempfile = "3"
