[package]
name = "litter"
license = "MIT OR Apache-2.0"
version = "0.20220713.0"
edition = "2021"

[dependencies]
bstr = "0.2.17"
once_cell = "1.13.0"
postcard = { version = "1.0.0", optional = true, features = ["use-std"] }
rkyv = { version = "0.7.39", optional = true }
serde = { version = "1.0.139", optional = true }
serde_json = { version = "1.0.82", optional = true }
serde_yaml = { version = "0.8.25", optional = true }
toml = { version = "0.5.9", optional = true }

[dev-dependencies]
serde_derive = "1.0.139"

[features]
json = ["dep:serde", "dep:serde_json"]
yaml = ["dep:serde", "dep:serde_yaml"]
toml = ["dep:serde", "dep:toml"]
